data_dir: "data/KinshipHinton"
model: "pRotatE"
trained_model_path: "models/pRotatE_KinshipHinton_dim50"
nav_epsilon_error: 9.811700820922852
nav_epsilon_metric: "l2"
freebaseqa_path: "data/KinshipHinton/kinship_hinton_qa_1hop"
raw_QAData_path: "data/KinshipHinton/kinship_hinton_qa_1hop.csv"
cached_QAMetaData_path: "./.cache/itl/kinship_hinton_qa_1hop.json"
rl_gamma: 0.9
nav_start_emb_type: "relevant"
num_rollout_steps: 2
batch_size: 6
batch_size_dev: 2
batches_b4_eval: 1
node_data_path: ""
node_data_key: ""
relationship_data_path: ""
relationship_data_key: ""
